name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
